"""
This module contains a mock flight API class that generates flight data based on the user
provided data.
"""

import random
from datetime import datetime, timedelta, time

class MockFlightAPI:
    """
    Mock flight API class to generate theoretical flight data based on user input and
    randomised data from a list of pre determined airlines and price bounds.
    The class contains a method to "search" (generate) for flights based on these parameters.
    """
    def __init__(self):
        self.flights = []

    def search_flights(self, origin, destination, date):
        """
        Method which generates the list of flights based on the parameters given by combining
        randomised data with the user input. Departure and arrival times are generated by
        obtaining a random number between certain values, airline generated by choosing a random
        one from the list of airlines, flight number created by combining airline with a random 3
        digit number.

        args:
            origin (str): The origin airport code.
            destination (str): The destination airport code.
            date (str): The date of the flight in ISO standard.
        
        Returns:
            List of generated flight dictionaries.
        """

        #Clears previous search results
        self.flights = []
        # Mock airlines
        airlines = ['Ryanair', 'British Airways', 'Tui', 'EasyJet']

        #Generates randomised flights
        for i in range(random.randint(1, 10)):
            dtime = time(random.randint(0, 23), random.randint(0, 59))
            atime = time(random.randint(0, 23), random.randint(0, 59))
            airline = random.choice(airlines)

            flight = {
                'fnumber': f'{airline} {random.randint(100, 999)}',
                'airline': airline,
                'origin': origin,
                'destination': destination,
                'date': date,
                'price': random.randint(100, 500),
                'dtime': dtime,
                'atime': atime
            }
            self.flights.append(flight)
        return self.flights